version: '3'

services:
  bedrock_server:
    image: bedrock_server:latest
    build: .
    container_name: bedrock_server
    ports: 
      - 19132:19132/udp
      - 19133:19133/udp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      # temporarily we are mapping the worlds folder to an import folder because when
      # mounting this volume in Windows at least the bedrock server crashes.
      # as this is running on a linux hostdisregard previous 
      #- ~/data/minecraft/worlds:/home/bedrock/bedrock_server/import/worlds
      - ~/data/minecraft/config:/home/bedrock/bedrock_server/config
      - ~/data/minecraft/worlds:/home/bedrock/bedrock_server/worlds
      
    # override the default entrypoint to include access to a bash terminal for debugging.
    entrypoint: bash -c "/home/bedrock/startup.sh && /bin/bash"
